Barsigns Competition
Fluffy-Frontier/FluffySTG pull request #1155
Opened 2023-12-16 19:21 UTC by RaShCat

<details>
<summary>Победитель 1:</summary>
  

https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/b84392f1-e09a-4d20-85f1-8569898ee033

</details>
<details>
<summary>Победитель 2:</summary>
  
https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/8e3fa45a-392f-481a-8fa4-108478ace42b

</details>

## Changelog
:cl:
add: Barsigns of discord competition now in game!
/:cl:

2023-12-16 19:22 UTC, RaShCat commented
Возможно юнит-тест не пройдёт и я выкачу дополнительную оверрайдину.

2023-12-16 19:35 UTC, RaShCat commented
Угусь. Сейчас подумаю как исправить.

2023-12-17 12:46 UTC, Iajret requested changes

2023-12-17 12:46 UTC, Iajret commented on code/modules/unit_tests/barsigns.dm
> +	barsign_icon_states += icon_states('tff_modular/modules/barsigns/icons/barsigns.dmi') // THE FLUFFY FRONTIER - Need to check modular barsigns
Пусть перенеси в `~ff_define` и тут его пропиши.

2023-12-17 12:46 UTC, Iajret commented on tff_modular/modules/barsigns/code/barsigns.dm
> +		icon = 'tff_modular/modules/barsigns/icons/barsigns.dmi'
И тут тоже. Если он используется в более чем одном месте - это точно надо отдельно в виде дефайна выносить.

2023-12-17 15:48 UTC, RaShCat commented on code/modules/unit_tests/barsigns.dm
> +	barsign_icon_states += icon_states('tff_modular/modules/barsigns/icons/barsigns.dmi') // THE FLUFFY FRONTIER - Need to check modular barsigns
Пока решил удалить его. Проверка на него вовсе не срабатывает. По идее.

2023-12-17 15:48 UTC, RaShCat commented on tff_modular/modules/barsigns/code/barsigns.dm
> +		icon = 'tff_modular/modules/barsigns/icons/barsigns.dmi'
А он видимо и не используется.

2023-12-17 15:50 UTC, RaShCat commented
Дождусь проверки. Не должно по идее сломать юнит тесты.

2023-12-17 18:56 UTC, Iajret approved these changes

2023-12-17 18:56 UTC, merged