Russian codewords for antagonists
Fluffy-Frontier/FluffySTG pull request #16
Opened 2023-05-03 19:33 UTC by RaShCat

## About The Pull Request
### Перевести код. фразы предателей и подсветить в чате. 
https://discord.com/channels/574254221004898335/797201199271116830/1090653854183460874

## Лень и конфликты.
  Я не стал переводить слова самостоятельно и прошу вас помочь мне в пересмотре их в файлике .json . 
А то как-то много на себя беру, заставляя всех игроков играть по своим словам! 

Так же было принято решение не переводить имена, т. к. игроки часто используют английские варианты для общения. Находят трупы на шахтах или спрашивают по общей частоте, есть ли он в списке экипажа. 

Так же и о должностях. Кодеры пришли к согласию, что пока мы оставим это так. 
## Подтверждаю тесты:
![изображение](https://user-images.githubusercontent.com/33174229/236022717-cde8648c-19d1-410b-bff0-808057da4341.png)

## Changelog
:cl:
add: Russian codewords for antagonists
code: Some changes in TG code for it. 
/:cl:

2023-05-04 21:08 UTC, RaShCat commented
Так. С кодом вопросы решили. Теперь осталось перебрать 700 слов. Ха-ха...

2023-05-04 22:38 UTC, RaShCat commented
Подождите. Я опять всё сломал.

2023-05-05 15:23 UTC, RaShCat commented
![изображение](https://user-images.githubusercontent.com/33174229/236500168-3b276b17-6db4-4380-84e6-fcd537160cfd.png)
Не знаю. Мне не платили и это я не трогал. Иногда будут проблемы с подсветкой. Но это уже к ТГшникам.

2023-05-05 15:44 UTC, RaShCat commented
Моя задача как кодера здесь закончена. Любые правки может сделать любой желающий, просто меняя ruscodewords.json. Всё.

2023-05-09 15:13 UTC, AnywayFarus requested changes
Ну, я что заметил на то и показываю. Было бы хорошо еще разок пробежаться по словам.

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "КЛЮЧЬ"
Ключ?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "Хууч",
Или хуч?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "Муншайн",
Или самогон?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "Вермуз",
Вермут?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "Водка с мортини",
с мартини?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "Сварочная топливо",
ОЕ?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "КОРГИС",
?

2023-05-09 15:13 UTC, AnywayFarus commented on tff_modular/modules/russiancodewords/strings/ruscodewords.json
> +        "ФЕДОРЫ",
Фёдоры).

2023-05-12 17:36 UTC, RaShCat commented
Квалификации не хватает на ремонт маркировки русского текста. Такие морковки.

2023-05-22 08:47 UTC, merged