Redsec returned
Fluffy-Frontier/FluffySTG pull request #18
Opened 2023-05-04 22:53 UTC by FeenieRU

## About The Pull Request

Возвращение редсека в виде шкафов и вендомата.

## How This Contributes To The Skyrat Roleplay Experience

Фэйшон. Гламоур. Робаст.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/62373791/236345939-37f9bb85-deb4-462f-a61d-83472871272e.png)
![image](https://user-images.githubusercontent.com/62373791/236345954-3140f699-c15a-491d-bcec-41cc099bbc92.png)

</details>

## Changelog

:cl:
add: Added Universal SecDrobe to brig
add: Added redsec officer closets to brig
image: added icons for closets and vends
code: Red SecDrobe and Universal SecDrobe are added in machine_circuitboards.dm
/:cl:

2023-05-04 22:54 UTC, FeenieRU commented
Пояс я поставил редсековский в шкаф

2023-05-04 23:04 UTC, FeenieRU commented
![image](https://user-images.githubusercontent.com/62373791/236348247-5e4e35d3-b8c3-4240-8eee-e181a7924e6e.png)
![image](https://user-images.githubusercontent.com/62373791/236348273-e32d9288-7104-48c0-a6aa-c9d0a67ca37d.png)
![image](https://user-images.githubusercontent.com/62373791/236348295-68cab772-4692-47f7-b135-87050f609687.png)

2023-05-05 04:49 UTC, masline147 commented
Почему нет брони Блюсека в автомате? Только high-light vest...

2023-05-05 08:30 UTC, FeenieRU commented
> Почему нет брони Блюсека в автомате? Только high-light vest... А изменил ли ты еще restoring unit заказывающийся в карго? Как будет время, так скину код...

Не менял, ибо так и планировал, чтобы у разных версий вардроба был одинаковый ресток. Но раз надо, сейчас сделаю.

2023-05-05 09:08 UTC, FeenieRU commented
![image](https://user-images.githubusercontent.com/62373791/236418894-0980ec01-1251-4efc-841f-c17e0fe1ede3.png)
![image](https://user-images.githubusercontent.com/62373791/236418927-83375fec-e106-497c-afd3-5d3fc305d6ec.png)

2023-05-05 11:44 UTC, masline147 commented
Не имею пока понятия как предлагать в пулл зменения в коде... В общем, добавь:
`/obj/item/clothing/suit/armor/vest/peacekeeper`

2023-05-05 11:50 UTC, masline147 commented
Спасибо...

2023-05-10 17:52 UTC, FeenieRU commented
Суть ПРа изменилась - теперь стандартный вендомат имеет переписанный ассортимент, а шкафы СБ рандомятся между редсеком и блюсеком. Правки исполнены.

2023-05-15 08:58 UTC, AnywayFarus requested changes
ну как та так

2023-05-15 08:58 UTC, AnywayFarus commented on tff_modular/modules/redsec/code/closets.dm
> +		new /obj/item/storage/belt/security/redsec/full(src)
```suggestion
		new /obj/item/storage/belt/security/redsec/full(src)

```

2023-05-15 08:58 UTC, AnywayFarus commented on tff_modular/modules/redsec/code/closets.dm
> +/obj/structure/closet/secure_closet/security/PopulateContents()
```suggestion
/obj/structure/closet/secure_closet/security/PopulateContents()
    . = ..()
```

2023-05-21 12:31 UTC, closed without merging