MercReaper's commission
Fluffy-Frontier/FluffySTG pull request #2196
Opened 2024-02-29 18:39 UTC by ReezeBL

## О Pull Request

Курточка в лоадаут. В летнем и зимнем варианте.
## Как это может улучшит/повлиять на игровой процесс/ролевую игру

Красивое..

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>
  
![image](https://github.com/Fluffy-Frontier/FluffySTG/assets/6696374/7d93da21-b728-41b2-b931-b150bed29767)
![image](https://github.com/Fluffy-Frontier/FluffySTG/assets/6696374/58e0c5d5-30e9-42b6-b7a8-e01dc2757747)
![image](https://github.com/Fluffy-Frontier/FluffySTG/assets/6696374/21ab8b83-f723-40a4-bcba-505add308278)

</details>

## Changelog

:cl:
add: Added commission jacket
/:cl:

2024-02-29 19:16 UTC, Iajret requested changes
Армадайн везде написан по разному. Армадайна в целом у нас вроде уже нет, но и лора тоже у нас нет. Ещё проверь своими глазками инглиш. Не могу совета по нему дать, так как сам плохо его знаю.

2024-02-29 19:16 UTC, Iajret commented on tff_modular/modules/~donator/clothes/donator_clothing.dm
> +	desc = "Long jacket developed by \"Armadayne\" for security officers. The Armadine logo is blue on the back. Made from materials to retain heat and can be used down to -20 Celsius."
```suggestion
	desc = "Long jacket developed by \"Armadyne\" for security officers. The Armadyne logo is blue on the back. Made from materials to retain heat and can be used down to -20 Celsius."
```

2024-02-29 19:16 UTC, Iajret commented on tff_modular/modules/~donator/clothes/donator_clothing.dm
> +	desc = "Long jacket developed by \"Armadain\" for security personnel working in harsh, low temperature conditions. Maintains body temperature at -40 Celsius. Armadine logo on the back in blue."
```suggestion
	desc = "Long jacket developed by \"Armadyne\" for security personnel working in harsh, low temperature conditions. Maintains body temperature at -40 Celsius. Armadyne logo on the back in blue."
```

2024-02-29 19:22 UTC, ReezeBL commented
> Армадайн везде написан по разному. Армадайна в целом у нас вроде уже нет, но и лора тоже у нас нет. Ещё проверь своими глазками инглиш. Не могу совета по нему дать, так как сам плохо его знаю.

Я уточню у Мерка этот момент вообще. Мб избавиться стоит от Армадайна. Он кстати есть, как производитель пушек. Вроооде бы.

2024-03-01 12:07 UTC, Iajret approved these changes

2024-03-01 12:07 UTC, merged