NTIS
Fluffy-Frontier/FluffySTG pull request #2523
Opened 2024-03-23 13:17 UTC by RaShCat

## О Pull Request

Полиция для НТРа, консоль для НТРа. Всё для НТРа. 

## Доказательства тестирования

<details>
<summary>Картиночке</summary>

![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/cc725b59-7d31-4455-a73e-c2d16234f2ce)

![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/77febaef-22fd-4e7d-9811-20a7de50fa44)

![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/b0a8280e-7c9e-4871-aba0-8d71437018d2)

![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/33174229/d269e96a-4141-41f4-9b4c-4c42428afaba)
  
</details>

## Changelog

:cl:
add: NTIS for NTR
add: Personal communication console for NTR
/:cl:

2024-03-25 11:56 UTC, RaShCat commented
Всё. Теперь точно всё. Если только косяки какие не найдёте.

2024-03-25 16:58 UTC, ReezeBL commented
Тут коммитов больше чем у меня в среднем в проекте целом..

2024-03-25 17:03 UTC, RaShCat commented
> Тут коммитов больше чем у меня в среднем в проекте целом..

Я... Я просто по выходным пилил. И на учёбе. Как только у меня запускался бьонд и не срал - я коммитил хD

2024-03-25 18:32 UTC, JlereHda3oHbl1984 commented
> Всё. Теперь точно всё. Если только косяки какие не найдёте.

за нахождение косяков предусмотрена статья уголовного кодекса

2024-03-25 21:10 UTC, Iajret requested changes
Вех получается. Мне лень думать, только это глаз порезало. Копипасту мы (наверное нет) как-нибудь потом посмотрим, можно ли поправить в адекватное. Плюс, я не смотрел жсх.

2024-03-25 21:10 UTC, Iajret commented on tff_modular/modules/modular_automapper/replacer.dm
> +						break
```suggestion
				if(!is_type_on_turf(candidate_turf, target_obj))
					continue
				//Нашли клетку где стоит наш объект под замену.
				var/obj/old_atom = pick(candidate_turf.get_all_contents_type(target_obj))
				// Направление меняем.
				var/obj/new_atom =  new desired_atom(candidate_turf)
				new_atom.setDir(old_atom.dir)
				qdel(old_atom)
				break
```
Почему-то два одинаковых ифа друг в друг + уменьшить вложение (инверсировал первый иф для этого. Проверь не сломается ли, я просто ящерица, я не знаю) + изменить названия переменных на нормальные, потому что `var/obj/some` это какой-то бред.

2024-03-26 05:03 UTC, RaShCat commented on tff_modular/modules/modular_automapper/replacer.dm
> +						break
Это не бред, это мне было грустно!

2024-03-26 16:33 UTC, Iajret approved these changes

2024-03-26 16:34 UTC, Iajret commented
ждём жидки фак-ап от нас в раунде 8273

2024-04-01 17:35 UTC, RaShCat commented
Оч надеюсь что ничего не сломал...

2024-04-16 15:41 UTC, merged