Xenoarchelology artifacts.
Fluffy-Frontier/FluffySTG pull request #3267
Opened 2024-05-09 18:29 UTC by Microvolnovka19

## О Pull Request

Добавляет артефакты из ТауКиты к нам, так как ксеноархеология в текущем состоянии - скучный кал, который даёт только "useless relic". Здесь же добавляются различные(пока что только один вид) артефакты, дающие разные эффекты, как полезные, так и потенциально очень разрушительные.
По факту инструкция с вики ТауКиты здесь применима, за исключением нескольких малых деталей, однако по большей части описания эффектов и способов активации везде верные.
Спавнятся они так же, как и обычные странные камни, но только с шансом 3%. В будущем думаю изменить шанс на 1%, но добавить сканер или маячки GPS.

![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/59139863/60de61ae-f56d-43bb-a044-a694328e8577)

## Чек-лист
- [x] Портировать артефакты-машины
- [x] Портировать все эффекты нужные эффекты артефактов-машин
- [x] Спавн странных булыжников вместо странных камней с шансом 3%
- [x] Раскопка булыжников. Стабилизация ( через Handheld recoverer )
- [x] Скан артефактов ( Реализовано через археологические сканеры )
- [x] Защита от воздействия ( Работает через проверку на Biohazard ) 
- [ ] Отдельная машинерия для изучения артефактов
- [ ] Прибор для "клонирования" эффекта в себя и выпуска
- [ ] Артефакт-клонер
- [ ] Артефакт-блю-бля-кристалл
- [ ] Артефакт-репликатор
- [ ] Артефакт-ховерпод (Надо будет забалансить. Он и на Тау был говном)

## Как это может улучшить/повлиять на игровой процесс/ролевую игру

Ксеноархеология скучный кал. Данный ПР:
1. Даёт возможность выбить как полезный инструмент, который можно применять на станции (массовый хилл в определённом радиусе, майнер редкого газа и т.д.)
2. Так и даёт возможность выбить опасное оружие(массовый урон в радиусе, емп, гравитавция и т.д.)
3. Даёт возможность ксеноархеологам реально повлиять на игру, т.к. раньше они этого сделать толком не могли и не привносили на станцию ничего, кроме 5k(или сколько там даётся за эксперименты?) научных очков.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>
  
![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/59139863/735202df-b9f8-4996-a551-983b957db223)
![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/59139863/38a4a793-87cc-4f2d-af8e-f0e15b49ad64)
![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/59139863/bd84a445-3ab5-4fc9-8360-f51e1602913f)
![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/59139863/b9bfdfcf-84ec-4205-8333-c690e46fc912)

</details>

## Changelog

:cl: SuperDrish
add: Портирование артефактов-машин с ТауКиты
/:cl:

2024-05-10 22:22 UTC, Iajret requested changes
Дальше я пока устааав. Как минимум - поудаляй везде эти проклятые лишние пробелы и табуляцию. На апстриме не любят однобуквенные переменные, так что эти твои `AM`, `O`, `W` и прочие тоже глянь. Я то прочитав контекст могу понять, что это, но всё же. Глобальные переменные на ТГ делаются иначе, тоже поправить бы. Выбор штуки при помощи веса - тоже поменять бы, чтобы было как и во всё коде используется... чо ищо там. Не помню. Посмотри какие дефайны проще в битфлаги перевести тебе будет, чтобы вместо обычных циферок было. Я правда не помню, сколько у нас битов вообще тут есть)

2024-05-10 22:22 UTC, Iajret commented on tff_modular/modules/xenoarcheology/artifact_machine.dm
> +	 (secondary_effect?.trigger >= TRIGGER_HEAT && secondary_effect.trigger <= TRIGGER_NITRO))
Причина, по которой лучше использовать битфлаги, вместо цифр. Ты мог бы использовать битовые операции и сделать этот иф... почище что ли. В дефах сделать там `#define TRIGGER_ATMOS (TRIGGER_HEAT | TRIGGER_COLD | TRIGGER_GASSES)` и через И по нему проверять. Я пока не уверен, стоит ли тебе все дефайны с циферок на флаги перенести, но триггеры явно стоит.

2024-05-10 22:22 UTC, Iajret commented on tff_modular/modules/xenoarcheology/artifact_machine.dm
> +			try_toggle_effects(TRIGGER_TOXIN)
Возможно стоит отдельные списки групп для химии написать и сравнивать сразу со списком этой группы. У нас же больше всякой разной фигни, чем на Тау, да?

А ещё водород - очень волатилен. :CatNerd:

2024-05-10 22:22 UTC, Iajret commented on tff_modular/modules/xenoarcheology/effect.dm
> +#define ARTIFACT_LARGE_POWER  3
```suggestion
#define ARTIFACT_SMALL_POWER 1
#define ARTIFACT_MEDIUM_POWER 2
#define ARTIFACT_LARGE_POWER 3
```

2024-05-10 22:22 UTC, Iajret commented on tff_modular/modules/xenoarcheology/effect.dm
> +	switch(pick(chance_small;ARTIFACT_SMALL_POWER, chance_medium;ARTIFACT_MEDIUM_POWER, chance_large;ARTIFACT_LARGE_POWER))
```suggestion
	var/artifact_power = pick_weight(list(ARTIFACT_SMALL_POWER = chance_small,
		ARTIFACT_MEDIUM_POWER = chance_medium,
		ARTIFACT_LARGE_POWER = chance_large,
	))
	switch(artifact_power)
```
Наверное опять лучше так??

2024-05-11 12:03 UTC, Microvolnovka19 commented on tff_modular/modules/xenoarcheology/artifact_machine.dm
> +			try_toggle_effects(TRIGGER_TOXIN)
В первом реагентов не то чтобы много. Во втором есть проверка на подтипы, то же самое и в четвёртом.

Для третьего сделал список

2024-08-01 01:14 UTC, closed without merging