Язык лунатиков
Fluffy-Frontier/FluffySTG pull request #3564
Opened 2024-05-30 13:33 UTC by JlereHda3oHbl1984

## О Pull Request

Язык лунатиков по баунти Вишни 
_лунодефки говорят на французском)) ВО УМОРА, НА ЛУНЕ ЖЕ НЕТ ЛЯГУШЕК, ЧЕ ОНИ ТАМ ЕДЯТ?))))))))))ХДДДДД_

## Как это может улучшить/повлиять на игровой процесс/ролевую игру

Это стильно, это молодёжно. По секрету скажу: мой дед и сам был Селестианским языком.

## Доказательства тестирования

<details>
<summary> Экшуалли, описание языка малясь другое. 
</summary>
  
![3LKOBxSxfls](https://github.com/Fluffy-Frontier/FluffySTG/assets/114810807/0e74f92e-4cf7-486e-a108-d8c56ca8b16c)
![X__S8jy3wAg](https://github.com/Fluffy-Frontier/FluffySTG/assets/114810807/df3cab78-1e51-4a7b-ad4a-dade03addc05)
![lg2wqDMG46k](https://github.com/Fluffy-Frontier/FluffySTG/assets/114810807/ed268d5a-326f-4b60-9270-c98131cce108)
![U3Wz5XrH8UE](https://github.com/Fluffy-Frontier/FluffySTG/assets/114810807/10af5698-e195-46fe-ad39-813cc7dc7228)
![Y1ckq4BBl5I](https://github.com/Fluffy-Frontier/FluffySTG/assets/114810807/c5ea2391-2d2e-4b25-a88b-7c3b8039e043)

</details>

## Changelog

:cl:
add: adds selestial language
/:cl:

2024-05-30 17:07 UTC, RaShCat commented
Le De Teshare Sdu~

2024-05-31 16:36 UTC, AstraFarera commented
Yhaaay! 
Light! Guide my Agh'rows!

Gimme gimme

2024-06-02 13:02 UTC, Iajret requested changes

2024-06-02 13:02 UTC, Iajret commented on tff_modular/modules/selestial_language/language_holder.dm
> +/datum/language_holder/synthetic
Давай ты просто добавишь лунатизмовый язык в `modular_nova\master_files\code\modules\language\language_holder.dm`, чтобы никто никого в рот больше не ебал.

2024-06-02 13:19 UTC, Iajret commented on tff_modular/modules/selestial_language/language_holder.dm
> +/datum/language_holder/synthetic
```DM
/datum/language_holder/synthetic/New()
  grant_language(/datum/language/selestial, source = LANGUAGE_ATOM)
```

или попробовать заменить всё то, что ты накалаякал на вот это

2024-06-02 22:55 UTC, Iajret approved these changes
Не сработало :(

2024-06-02 22:56 UTC, merged