Кастомные задачи
Fluffy-Frontier/FluffySTG pull request #3912
Opened 2024-06-19 06:26 UTC by SSensum

## О Pull Request

Добавляет в билд возможность создания кастомных задач, которые указываются в json-конфиге, которые выдаются антагонистам в соотношении 1 к 1 с их обычными задачами.

## Как это может улучшить/повлиять на игровой процесс/ролевую игру

Кастомные, немеханические задачи - это круто для ролеплея.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>
  
![7wiDVkL4Ho](https://github.com/Fluffy-Frontier/FluffySTG/assets/121913313/16b44d06-985b-44ab-b3cf-c852a6a07d3e)

</details>

## Changelog

:cl:
add: [FF-ONLY] Added support for custom, non-mechanical objectives.
/:cl:

2024-06-19 13:48 UTC, ReezeBL commented
Мб это и не нужно, но все изменения в основном коде можно подцепить модульно..

2024-06-19 14:01 UTC, SSensum commented
> Мб это и не нужно, но все изменения в основном коде можно подцепить модульно..

Я намеренно оставил там, чтобы в случае если логика измениться в выдаче антажек - вы бы получили мержкомит, а не внезапный рантайм.

2024-06-20 09:29 UTC, Iajret requested changes
бу-бу-бу, меняем комменты, бу-бу-бу (так искать проще, чем по двум буковкам ФеФе)

2024-06-20 09:29 UTC, Iajret commented on code/modules/antagonists/_common/antag_datum.dm
> +	var/skip_custom_objectives_addition = FALSE // FF ADDITION - CUSTOM OBJECTIVES
```suggestion
	var/skip_custom_objectives_addition = FALSE // FLUFFY FRONTIER ADDITION - Custom Objectives
```

2024-06-20 09:29 UTC, Iajret commented on code/modules/antagonists/_common/antag_datum.dm
> +		add_custom_objectives() // FF ADDITION - CUSTOM OBJECTIVES
```suggestion
// FLUFFY FRONTIER CHANGE START- Custom Objectives
	if(!skip_custom_objectives_addition)
		add_custom_objectives()
// FLUFFY FRONTIER CHANGE END
```

2024-06-20 09:29 UTC, Iajret commented on code/modules/antagonists/brother/brother.dm
> +	skip_custom_objectives_addition = TRUE // FF ADDITION - CUSTOM OBJECTIVES
```suggestion
	skip_custom_objectives_addition = TRUE // FLUFFY FRONTIER ADDITION - Custom Objectives
```

2024-06-20 09:29 UTC, Iajret commented on code/modules/antagonists/brother/brother.dm
> +		add_custom_objectives() // FF ADDITION - CUSTOM OBJECTIVES
```suggestion
		add_custom_objectives() // FLUFFY FRONTIER ADDITION - Custom Objectives
```

2024-06-20 09:50 UTC, Iajret requested changes
Эти вещи я бы тоже сам мог закоммитить. они слишком мелкие. Но лучше проверь, а то вдруг ящерица опять зафакапит :)

2024-06-20 09:50 UTC, Iajret commented on tff_modular/modules/custom_objectives/code/custom_objectives.dm
> +		.[antag_path] = list()
```suggestion
	for(var/antag_name as anything in GLOB.antags_to_names)
		var/antag_path = GLOB.antags_to_names[antag_name]
		.[antag_path] = list()
```
Это переменная нигде не используется, а лист ты всё равно не модифицируешь. Так и надо???

2024-06-20 09:50 UTC, Iajret commented on tff_modular/modules/custom_objectives/code/custom_objectives.dm
> +	if(custom_objs == null || length(custom_objs) == 0)
```suggestion
	if(isnull(custom_objs) || !length(custom_objs))
```

2024-06-20 09:50 UTC, Iajret commented on tff_modular/modules/custom_objectives/code/custom_objectives.dm
> +	if(custom_objs == null || length(custom_objs) == 0)
```suggestion
	if(isnull(custom_objs) || !length(custom_objs))
```

2024-06-22 11:05 UTC, SSensum commented
@Iajret, что ещё осталось то? Когда мерж?

2024-06-23 16:47 UTC, SSensum commented on tff_modular/modules/custom_objectives/code/custom_objectives.dm
> +		.[antag_path] = list()
> Это переменная нигде не используется, а лист ты всё равно не модифицируешь. Так и надо???

Я предположил, что глоб списки работают по типу мапы, так что присвоил изначально значение переменной, дабы не дублировать вызовы того или иного списка.

2024-08-24 11:27 UTC, merged