Da fix
Fluffy-Frontier/FluffySTG pull request #47
Opened 2023-06-15 00:33 UTC by HWSensum

## О Pull Request

Данный ПР восстанавливает "валидное" и пригодное состояние МКРов, позволяя перезаряжать их.

## Как это может улучшит/повлиять на игровой процесс/ролевую игру

МКР больше не будут игрушкой которая валяется в арсенале до момента тотальной прокачки или покупки речарджер аттачмента.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>

![dreamseeker_CFSFfOjNJ4](https://github.com/Fluffy-Frontier/FluffySTG/assets/121913313/82096ff4-125a-45aa-9a47-dcf173812465)
  
</details>

## Changelog

:cl:
balance: МКР вновь могут быть перезаряжены без разрядки батареи.
/:cl:

2023-06-15 07:04 UTC, Kush1Push1 commented on tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
> +/obj/item/gun/microfusion/insert_cell(mob/user, obj/item/stock_parts/cell/microfusion/inserting_cell, display_message = TRUE)
Имхо, лучше не модулем сделать, а закоментировать оригинал. Усложняет поиск и работу с кодом, а также наглядность изменений

2023-06-15 08:28 UTC, AnywayFarus commented
Не прочитана форма PR'a.

2023-06-15 08:32 UTC, AnywayFarus requested changes

2023-06-15 08:46 UTC, RaShCat commented on tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
> +/obj/item/gun/microfusion/insert_cell(mob/user, obj/item/stock_parts/cell/microfusion/inserting_cell, display_message = TRUE)
Имхо. Просьба всегда одна: максимально модульно.

2023-06-15 16:13 UTC, HWSensum commented on tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
> +/obj/item/gun/microfusion/insert_cell(mob/user, obj/item/stock_parts/cell/microfusion/inserting_cell, display_message = TRUE)
> Имхо, лучше не модулем сделать, а закоментировать оригинал. Усложняет поиск и работу с кодом, а также наглядность изменений

Куши, не умничай. Мне на нервы действуют твои amateur выскоки. Я сделал так, ибо Вишня не любит решать мержконфликты и просит делать всё максимально модульно. В начале изменённых файлов я написал то, где искать перезаписи в случае ошибок или иных причин.

2023-06-15 16:15 UTC, HWSensum commented on tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
> +	do_sparks(4, FALSE, src)
От части да. Я предпочёл бы не удалять эти проки, а сделать из них такие вот заглушки, чтобы как можно меньше влиять на изначальный код.

2023-06-15 16:16 UTC, HWSensum commented on tff_modular/modules/mcr_nerf_revert/code/mcr_override.dm
> +	update_appearance()
Это изменение Внешки батареи, а не МКРа. Чтобы когда ты её вытаскиваешь - она точно имела бы правильный спрайт.

2023-06-16 17:02 UTC, AnywayFarus approved these changes

2023-06-16 17:20 UTC, merged