GAS carry build late game
Fluffy-Frontier/FluffySTG pull request #4957
Opened 2024-08-23 15:40 UTC by Oxotnak

## О Pull Request
Мне были одобрены внесения множества изменений что-бы сделать ГБСов лучше механически и косвенно более требовательными к ролеплею с ними/за них.

**Current roadmap:**
- [ ] Выдать иммунитет к плазме, убрать возможность дышать через баллон, убрать слот маски, добавить отдельный орган который будет синтезировать окси реген химию до n лимита и позволит находиться в вакууме ограниченное время, а так же затруднит применение мультивера/пентетика
- [ ] Выдать базовый ноуслип, лёд и смазка всё ещё будут работать
- [ ] Выдать мгновенный агрессив граб в режиме кос
- [ ] Выдать иммунитет к боллам и капкану
- [ ] Выдать полёт над пустыми тайлами (ямы, многоуровневые станции) либо скилл молей на перемещение между уровнями
- [ ] Переместить мозг из головы в тело согласно биологии
- [ ] Поднять скорость в режиме угрозы
- [ ] Уменьшить время активации кос и/или дать возможность активировать в движении
- [ ] Дать возможность перехода в боевой режим в наручниках

## Как это может улучшить/повлиять на игровой процесс/ролевую игру
В текущем положении никто ничуть их не боится, плевать что это хищник и они "нестабильны", особенно при минусовом темпераменте. Даже если придётся с ними драться они лишь больно режут, а если и умрёшь то тебя просто поднимут в медбее, терять нечего. Но вот на бее тебя так просто никто не поднимет и люди там по настоящему боятся и опасаются их. Усиление механа приведёт к тому что всячески провоцировать серпентидов будет опаснее и провокатор рискует уехать в медбей.
Как механ повлияет на ролеплей? У людей будет больше мотивации ОБЩАТЬСЯ с настороженным серпентидом и успокаивать его. Если всё дойдёт до нападения.. Вы можете попробовать судить серпентида, устроить лекцию об попытке объяснить ему как работает закон? Возможностей выстроить ролеплей на этой основе полно, нужно лишь желание, а мы на мрп сервере всё таки.
Так же усиление их механически даст им возможно так или иначе противостоять массовым угрозам. Не в прямом смысле, вы не можете приказать серпентиду грызть красные/чёрные риги, как и он не может делать это вне самозащиты. Но у него будет хотя бы какая-то возможность защищаться за неимением возможности напрямую воевать с ними из-за рамок отыгрыша. Мне кажется немного нечестно если расе, которая сильно зависима от отыгрыша, никак нельзя проконтачить с угрозами которые педали могут решить спавнить три раунда подряд попросту лишая возможности играть конкретных людей.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>

</details>

## Changelog

:cl:
add: GAS now able to grab in scythes
/:cl:

2024-08-23 16:58 UTC, Iajret commented
based

2024-09-10 13:20 UTC, Oxotnak commented
![image](https://github.com/user-attachments/assets/0668c7bb-0a42-48d8-b1fc-01976ea0e56c)

2024-09-15 08:12 UTC, Microvolnovka19 requested changes
Это должно пофиксить тесты

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +	var/obj/item/restraints/legcuffs/gas_placeholder/anti_cuffs
```suggestion

```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +		C.equip_to_slot(anti_cuffs, ITEM_SLOT_LEGCUFFED, initial = TRUE)
```suggestion
		C.uncuff()
		if(!C.legcuffed)
			var/obj/item/restraints/legcuffs/gas_placeholder/anti_cuffs = new()
			C.equip_to_slot(anti_cuffs, ITEM_SLOT_LEGCUFFED, initial = TRUE)
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +
```suggestion

```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +		H.equip_to_slot(anti_cuffs, ITEM_SLOT_LEGCUFFED, initial = TRUE)
```suggestion
	if(H.num_legs >= 2 && !H.legcuffed && !QDELETED(H))
		var/obj/item/restraints/legcuffs/gas_placeholder/anti_cuffs = new()
		H.equip_to_slot(anti_cuffs, ITEM_SLOT_LEGCUFFED, initial = TRUE)
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +
```suggestion

/mob/living/carbon/human/Destroy()
	if(isnabber(src) && !QDELETED(legcuffed))
		QDEL_NULL(legcuffed)
	. = ..()
	
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/_nabbers.dm
> +	if(isnabber(src) && quirktype in bad_nabber_quirks)
```suggestion
	if(isnabber(src) && (quirktype in bad_nabber_quirks))
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/nabber_bolaimmunity.dm
> +	return FALSE
```suggestion
	INVOKE_ASYNC(src, PROC_REF(touch_ze_bug), stripper, owner)
	return ..()
	
/obj/item/restraints/legcuffs/gas_placeholder/proc/touch_ze_bug(mob/stripper, mob/owner)
	owner.visible_message(
						  span_purple("[stripper] сочно жамкает хвост ГБСа."),
						  span_purple("[stripper] лапает мой хвост!"),
						  blind_message = span_hear("You hear lewd bug noises."),
						)
	playsound(get_turf(owner), 'modular_nova/modules/modular_items/lewd_items/sounds/vax2.ogg', 50, TRUE)
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/nabber_language.dm
> +	if(isnabber(target))
```suggestion
	if(isnabber(target) && !QDELING(target))
```

2024-09-15 08:12 UTC, Microvolnovka19 commented on tff_modular/modules/nabbers/code/nabber_language.dm
> +	if(isnabber(target))
```suggestion
	if(isnabber(target) && !QDELING(target))
```

2024-09-17 12:38 UTC, Oxotnak commented
Рабочий список языков:
![Screenshot_62](https://github.com/user-attachments/assets/31143d97-2b3c-4b5a-8617-f8d956518c0f)
Пруф работы блеклиста: (в видео выбран этот перк)
![Screenshot_63](https://github.com/user-attachments/assets/fdf3e011-45d9-42c7-8bb6-ab922112b7b5)
Ингейм языки:
![Screenshot_64](https://github.com/user-attachments/assets/b5171402-c9b3-4867-85e9-49d55635a105)

2024-09-17 12:39 UTC, Oxotnak commented
Обзор новых добавленных фич:
https://youtu.be/r1o8oF6R8eg

2024-12-19 15:46 UTC, merged