Микроапдейт редсека
Fluffy-Frontier/FluffySTG pull request #4988
Opened 2024-09-03 13:54 UTC by delingar

## О Pull Request

Фикс и добавление редсек вариации для ботинков и разгрузки миротворца. Технически, редсек вариация разгрузки - версия разгрузки для ЕРТ Армадайна, но их никогда никто не видел у нас на сервере. Это миф.
## Как это может улучшить/повлиять на игровой процесс/ролевую игру

БОЛЬШЕ РЕДСЕКА БОГУ РЕДСЕКА

## Доказательства тестирования

Добавлю позже, у меня сейчас нет света.
<details>
<summary>Скриншоты/Видео</summary>

</details>

## Changelog

:cl:
add: Добавлены редсек версии для ботинков и разгрузки миротворца.
/:cl:

2024-09-03 13:58 UTC, Oxotnak commented
У редсек шлема всё ещё невидимый спрайт при добавлении фонарика

2024-09-03 14:10 UTC, delingar commented
> У редсек шлема всё ещё невидимый спрайт при добавлении фонарика

А я все ещё хз как это чинить :blep:

2024-09-04 10:08 UTC, Iajret requested changes
Я уже добавлял этот скин разгрузки. Он выше, вот тут:
https://github.com/Fluffy-Frontier/FluffySTG/blob/aa8836c46dc8f961dbcd3305c7ff9e5a362816d7/tff_modular/modules/redsec_reskins/code/redsec.dm#L269
почини его, раз уж не работает. 

И да - добавлять полный путь до файла иконок - лишнее. Можешь обойтись только с флагами `...ICON_STATE...` Будет тоже работать (так как пути до обоих скинов одинаковые и путь скина самой разгрузки совпадает с ними)

2024-09-04 10:09 UTC, Iajret commented
> У редсек шлема всё ещё невидимый спрайт при добавлении фонарика

Запретить добавлять фонарик при рескине. :CatBleh:

2024-09-04 11:30 UTC, delingar commented
Добавил рескины для перчаток, что упали с ТГ, пруфы добавлю позже, ибо снова нет света

2024-09-04 11:42 UTC, delingar commented
> Я уже добавлял этот скин разгрузки. Он выше, вот тут:
> 
> https://github.com/Fluffy-Frontier/FluffySTG/blob/aa8836c46dc8f961dbcd3305c7ff9e5a362816d7/tff_modular/modules/redsec_reskins/code/redsec.dm#L269
> 
> 
> почини его, раз уж не работает.
> И да - добавлять полный путь до файла иконок - лишнее. Можешь обойтись только с флагами `...ICON_STATE...` Будет тоже работать (так как пути до обоих скинов одинаковые и путь скина самой разгрузки совпадает с ними)

Я сделяль

2024-09-06 22:12 UTC, merged