healing_buff
Fluffy-Frontier/FluffySTG pull request #5099
Opened 2024-10-14 17:10 UTC by mogeoko

## О Pull Request

Баффает аптечку щитам, заменяя обычные слабые хилки на продвинутые + заменяется сканер на улучшенную версию + дается по 2 медипена на каждый тип урона. Всё помещается в коробку.

Дайте мне знать, если мне нужно перенести это в наш модуляр (желательно описать как это сделать).
Так же принимаются любые правки. По запросу Маслинушки и возможно других бщ.

## Как это может улучшить/повлиять на игровой процесс/ролевую игру

У элитного бойца будет более менее вразумительная аптечка на ряду с оружием.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>

![изображение](https://github.com/user-attachments/assets/9ecdb919-b163-4133-aa92-47f81ccb8cbc)

</details>

## Changelog

:cl: mogeoko
balance: Added more medicine to Blueshield's medkit
/:cl:

2024-10-14 20:12 UTC, mogeoko commented
Упд:
![изображение](https://github.com/user-attachments/assets/5dd32bdd-415c-482e-a24c-d15f7c50f651)

2024-10-16 11:37 UTC, mogeoko commented
P.S. решите между собой (педалями) какие штуки вы хотите видеть в аптечке. Я могу разделить их на несколько наборов и дать бщ маячок выбора.

2024-10-17 22:07 UTC, Iajret requested changes

2024-10-17 22:07 UTC, Iajret commented on modular_nova/modules/blueshield/code/medkit.dm
> +		/obj/item/reagent_containers/hypospray/medipen/oxandrolone = 2,
```suggestion
		/obj/item/reagent_containers/medigel/libital = 1,
		/obj/item/reagent_containers/hypospray/medipen/salacid = 1,
		/obj/item/reagent_containers/medigel/aiuri = 1,
		/obj/item/reagent_containers/hypospray/medipen/oxandrolone = 1,
```

2024-10-17 23:03 UTC, merged