Teshari job limitations
Fluffy-Frontier/FluffySTG pull request #5113
Opened 2024-10-18 12:34 UTC by ReezeBL

## О Pull Request

Тешарьбам обрезана возможность быть ГСБ, офицером, и щитом.

## Как это может улучшить/повлиять на игровой процесс/ролевую игру

Бриг больше не сможет использовать ГСБ для игры в футбол??? Наверное..

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>
![image](https://github.com/user-attachments/assets/794e04f4-64cf-4586-9d0b-fa9ee31ef80a)

</details>

## Changelog

:cl:
del: Teshari can not join round as HoS, Security Officer and Blueshield.
/:cl:

2024-10-18 12:42 UTC, mogeoko commented
ТУДА ИХ

2024-10-18 12:54 UTC, FeenieRU requested changes

2024-10-18 12:54 UTC, FeenieRU commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
?

2024-10-18 12:54 UTC, FeenieRU commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
??

2024-10-18 12:54 UTC, FeenieRU commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
???

2024-10-18 19:33 UTC, mogeoko commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
https://discord.com/channels/574254221004898335/1145096716211736698/1296785868560011325

2024-10-18 19:33 UTC, mogeoko commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
https://discord.com/channels/574254221004898335/1145096716211736698/1296785868560011325

2024-10-18 19:34 UTC, mogeoko commented
Request changes провален успешно, голосование педалей пройдено.

2024-10-19 07:09 UTC, FeenieRU commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
Доделывай уж блэклист

2024-10-19 07:36 UTC, mogeoko commented
Вот это 1984, понимаю

2024-10-19 07:36 UTC, mogeoko commented
Вот это 1984, понимаю

2024-10-19 07:41 UTC, mogeoko commented
Для контекста и мастерского удаления моих комментариев: варден, детектив и коррекционщик не идут в прямую стычку.

2024-10-19 09:12 UTC, FeenieRU commented
> Для контекста и мастерского удаления моих комментариев: варден, детектив и коррекционщик не идут в прямую стычку.

Для контекста и мастерской манипуляции: были удалены повторяющиеся сообщения и очередной наплак.
Варден всё ещё является промежуточным званием, так ещё и тем, кто имеет право на командование над боевым персоналом. Детектив же не переставал быть боевой ролью.

2024-10-19 09:37 UTC, FeenieRU commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
![изображение](https://github.com/user-attachments/assets/01aaf395-9d39-4757-8486-7d3a2ba71c83)

2024-10-19 09:52 UTC, ReezeBL commented on tff_modular/master_files/code/modules/job/job_blacklist.dm
>  	species_blacklist = list(SPECIES_NABBER = TRUE)
Кудах-тах-тах наседка брига тоже обрезана. 🤙

2024-10-19 09:58 UTC, mogeoko commented
Манипулятор 3000 пишет: Уважаемый ФинеРу, детективу запрещено сражаться до определенного момента ровно как и обычным членам экипажа. Пожалуйста, обсудите с администрацией как и кого вы хотите изменить, а не применяйте один и тот же вопросительный знак в трех местах без использования русского языка.

2024-10-19 10:03 UTC, FeenieRU commented
> Манипулятор 3000 пишет: Уважаемый ФинеРу, детективу запрещено сражаться до определенного момента ровно как и обычным членам экипажа. Пожалуйста, обсудите с администрацией как и кого вы хотите изменить, а не применяйте один и тот же вопросительный знак в трех местах без использования русского языка.

Не приравнивай детектива к ополчению, он свободно приводится в боевое действие без него по приказу начальника, в отличии от обычного экипажа.

2024-10-19 10:05 UTC, mogeoko commented
Ок
![изображение](https://github.com/user-attachments/assets/447afc9a-e71d-47ce-bb6a-053025270071)

2024-10-19 10:07 UTC, FeenieRU commented
Ок.

![изображение](https://github.com/user-attachments/assets/55a19d44-4a14-4668-a73e-4e4b17628f0c)

2024-10-19 10:12 UTC, Iajret commented
каждый день мы всё дальше от Бога

2024-10-19 10:12 UTC, merged