Небольшой ремап NSS Journey / Box Station.
Fluffy-Frontier/FluffySTG pull request #5122
Opened 2024-10-26 11:42 UTC by Smol42

## О Pull Request

hh beep bip

ПР вносит следующие изменения:

Обновление интерьера: 

> офис АВД, зал суда, бар, санитарные помещения, фитнес-зона, коридор между фитнес-зоной и санитарными комнатами, кабинет мима и клоуна, гражданская гидропоника и изолятор.

Другие изменения: 

> Коридор между санитарными помещениями и крио незначительно расширен.
> Офис АВД уменьшен для увеличения площади зала суда.
> Пространство гражданской гидропоники было слегка сокращено.
> Добавлен переходной коридор между офисом НТР, бригом и камерой суда.
> Скорректированы несколько дверей с стандартными названиями шлюзов и названиями "s."
> Добавлены недостающие доступа для нескольких дверей внутри брига.

<details>
<summary>Основные различия</summary>

</details>

[NEW

![NEW](https://github.com/user-attachments/assets/054336c3-5d46-4a83-884e-6d21fb62d723)

[OLD

![OLD](https://github.com/user-attachments/assets/e5c8c7ae-7134-4684-803d-21a854abe59f)

<details>
<summary>Гидропоника и изолятор</summary>

[NEW

![HYDRO_NEW](https://github.com/user-attachments/assets/28114640-eed3-41a1-adb5-21f1b350ef7e)
[OLD

![HYDRO_OLD](https://github.com/user-attachments/assets/ded53921-cf27-40fc-bfb0-f9ecee227935)
[NEW

![ISO_NEW](https://github.com/user-attachments/assets/87b0717a-592e-42d6-bbf6-ee31180154b8)
[OLD

![ISO_OLD](https://github.com/user-attachments/assets/9105b681-c49d-415b-93a0-11be492ac10c)

</details>

## Changelog

:cl: Smol42
map: did a slight NSS Journey / Box Station remap.
/:cl:

2024-10-27 14:39 UTC, Iajret requested changes
Ну я крестики решил, но одна вещь мне очень глаз режет. Эта комната ожидания и прилегаюшие к ней "теха". Три проблемы с ней. Две функциональные, одна... ролеплякная.
![image](https://github.com/user-attachments/assets/c449aec6-c4ff-4499-b823-086987dd871d)
1) Трубы в стенках - это страшный сон любого инженера. А тут эти стенки ещё и укреплённые. Их бы как-то убрать из стен. Может - добавить двери стоит. Или убрать трубы из пипки с ключом. Я б в красных кружках тупо двери техов напихал. Или даже коридорчики мб, хз.
2) следует из первого, по сути: мулбот (кто их использует???) не имеет валидного маршрута для доставки в бриг. Ты теха для него заменила на комнатку. Либо куда-то в другой место тогда перенести (к допроске?), либо добавить двери.
3) А в чём, в общем-то, смысл комнаты? Там есть кофе. Кресла. И клеточка для подсудимого. Зайти туда могут щит, нтр и СБ. Ведёт она... а никуда не ведёт. Выход в суд там только для подсудимо. Хотя кресло должно использоваться и свидетелями. Чтобы им туда попасть - им надо проходить через бриг или НТРа, через коморку первую с заключённым, через вторую коморку и только потом сядут в кресло. Это, имхо, неудобно будет (а ещё надо толкаться в комнатке два на два с человеком, который хотел тебя даблой порубить). НТР, который, наверное, будет судьёй - не имеет прямого хода в суд. Либо через адвоката, либо как все плебсы (не знаю, минус это или нет) придётся заходить.

2024-10-29 10:42 UTC, Smol42 commented
1. Стены были очищены от труб;
2. Мулбот теперь будет радовать посетителей в фойе детектива;

![image](https://github.com/user-attachments/assets/00a541d1-50dd-42dc-8167-91a9326a70e2)

3.  Добавлен дополнительный вход в суд. (2)

![image](https://github.com/user-attachments/assets/a5efd158-af37-4900-8d36-77d425290cc8)

2024-10-30 15:52 UTC, FeenieRU requested changes
https://github.com/Fluffy-Frontier/FluffySTG/issues/4969

Чекни пожалуйста ишью, остался ли на Джорни эта проблема

2024-10-31 10:30 UTC, Smol42 commented
> #4969
> 
> Чекни пожалуйста ишью, осталась ли на Джорни эта проблема

bip bip
-  Переместила техфаб и верстак для боеприпасов в "Офис службы безопасности". На местах где они находились раньше ( "Помещение для оборудования" ) теперь красуются столы.

2024-11-03 10:22 UTC, FeenieRU approved these changes
В целом теперь пофикшено и играемо

2024-11-04 06:03 UTC, merged