Поднимаем урон ТГ антагов (в поисках идеала в баладе о крысопушках)
Fluffy-Frontier/FluffySTG pull request #5159
Opened 2024-11-06 15:31 UTC by Axidyuwu

## О Pull Request
Урон еретических серпов поднимаем с 20 до 28, проклятого серпа с 25 до 32
Поднимаем урон многих боевых заклинаний еретика на 10-15
Еретик пепла теперь кидает в стаминакрит при ударе по метке как и должен
Поднимаем урон light eater с 25 до 30
Поднимаем максимальный урон void eater с 25 до 35

## Как это может улучшить/повлиять на игровой процесс/ролевую игру
"Крысопушки имба" и так далее, как одно из возможных решений поднятие статов у обязательных антаг вещей с ТГ.

## Доказательства тестирования
Пару измененных циферок, не столь сложно

<details>
<summary>Скриншоты/Видео</summary>

</details>

## Changelog

:cl:
balance: Damage buffs for herethic, void walker and nightmare items or spells
/:cl:

2024-11-06 15:49 UTC, FeenieRU requested changes

2024-11-06 15:49 UTC, FeenieRU commented on code/modules/antagonists/heretic/items/heretic_blades.dm
> +	force = 28 //Fluffy edit, original 20
Неправильный формат комментов, сделай в таком ключе:
`// FLUFFY FRONTIER EDIT: ANTAG BUFF #5159; original: 20`

2024-11-06 16:18 UTC, Axidyuwu commented on code/modules/antagonists/heretic/items/heretic_blades.dm
> +	force = 28 //Fluffy edit, original 20
Done

2024-11-06 16:35 UTC, FeenieRU requested changes

2024-11-06 16:35 UTC, FeenieRU commented on code/modules/antagonists/heretic/status_effects/mark_effects.dm
> +		carbon_owner.adjustStaminaLoss(17 * repetitions) // first one = 30 stam // FLUFFY FRONTIER EDIT: ANTAG BUFF #5159; original: 6
Тут надо поправить

2024-11-06 16:40 UTC, Axidyuwu commented on code/modules/antagonists/heretic/status_effects/mark_effects.dm
> +		carbon_owner.adjustStaminaLoss(17 * repetitions) // first one = 30 stam // FLUFFY FRONTIER EDIT: ANTAG BUFF #5159; original: 6
> Тут надо поправить

Если правильно понял - готово

2024-11-21 19:15 UTC, SSensum commented
нихуя себе. Ну давайте тогда апнем дубинки до ТГшных, чтобы они с двух ударов в стамкрит кидали, а не с 4.

2024-12-19 16:09 UTC, merged