Кастомный аналог ревы: Активисты
Fluffy-Frontier/FluffySTG pull request #53
Opened 2023-06-27 19:46 UTC by HWSensum

## О Pull Request

Данный ПР добавляет крайне универсальную антажку, своего рода аналог ревы, преимуществом которого является высокая кастомизация и отсутствие форсконвертов. 

Преимущества над обычной ревой:
- Кастомизация названий.
- Кастомизация задания.
- Настройка игнорирований импланта защиты разума.
- Возможность создания в одном раунде двух разных объединения/команды, которые будут иметь разные цели и НЕ будут друг-друга видеть по антаг-худу.

## Как это может улучшит/повлиять на игровой процесс/ролевую игру

Данная роль позволит реализовать бесконечное множество разных идей, ведь ввиду огромной кастомизации, вы можете использовать данную роль для любого рода мероприятий и ивентов, которые могут быть вообще не связаны с захватом станции.

## Доказательства тестирования

<details>
<summary>Скриншоты/Видео</summary>

![dreamseeker_fYlmxt5XKr](https://github.com/Fluffy-Frontier/FluffySTG/assets/121913313/74d6171d-b60b-4944-9013-1409a63e853b)

</details>

## Changelog

:cl:
add: New Activist antag role!
/:cl:

2023-06-27 21:47 UTC, AnywayFarus commented
Это история о сложном выборе, русский или английский?
Дам подсказку, двигайся в сторону второго.

В паре-трех файлах файлы кончаются лишними пустыми строками, зачем?
Ну это пока на быстрый лад осмотр, потом поподробнее гляну, но уже сейчас можешь заняться замечаниями выше, ну и имена переменных.

2023-06-27 22:16 UTC, HWSensum commented
> Это история о сложном выборе, русский или английский? Дам подсказку, двигайся в сторону второго.
> 
> В паре-трех файлах файлы кончаются лишними пустыми строками, зачем? Ну это пока на быстрый лад осмотр, потом поподробнее гляну, но уже сейчас можешь заняться замечаниями выше, ну и имена переменных.

Тут дело такое. Я старался писать на русском наиболее важные и длинные пояснения, чтобы те кто не умеет в английский - могли хотя бы понять что да как. Всё остальное я старался делать на английском.

2023-06-27 22:19 UTC, HWSensum commented
Исправил говно с форматированием, из-за которого были пустые строки.

2023-06-29 12:56 UTC, AnywayFarus commented
Еще помимо неувиденного мной на гифе кастомайза, хочу кастомайз и всплывающего окна, с изначальным текстом на английском. (заголовок, кнопки, текст)

2023-06-30 20:25 UTC, HWSensum commented
> Еще помимо неувиденного мной на гифе кастомайза, хочу кастомайз и всплывающего окна, с изначальным текстом на английском. (заголовок, кнопки, текст)

Зачем? Зачем тебе это на английском делать? Это увидят только педали и им будет удобнее видеть понятный текст на английском.

2023-06-30 20:25 UTC, HWSensum commented
А на счёт кастомизации, то ты можешь спокойно увидеть то, что там указывается в коде.

2023-06-30 21:40 UTC, HWSensum commented
В общем, я всё, кроме педальных менюшек, перевёл на английский.

2023-07-11 19:11 UTC, AnywayFarus commented
Посмотрев на методы использования.
Думаю надо добавить ЕЩЕ КАСТОМАЙЗА, ну по крайней мере раз для такого механ нужен, а не просто ролеплака.
надо крч, шобы этот буклет был изменяемым, т.е. спрайт и имя, а то вон.. фанатики, там можно и по другому было оформить, аля скрижаль чи просто свиток.

2023-07-13 20:52 UTC, Iajret commented on tff_modular/modules/custom_revolution/code/rev_team_role.dm
> +	member_name = "\improper activists"
Мелкопридирка, где-то тут написать в единственном числе, ведь экран конца раунда сам sку добавляет

2023-07-13 21:08 UTC, HWSensum commented on tff_modular/modules/custom_revolution/code/rev_team_role.dm
> +	member_name = "\improper activists"
уже изменено

2023-07-21 14:46 UTC, HWSensum commented
И так, функционал расширен.

Добавлена возможность деконверта с помощью машинерии специальной.

2023-07-25 01:45 UTC, Iajret requested changes
Мне не нравится, что это тупо копипаста, но поправь хотя бы эти две строчки

2023-07-25 01:45 UTC, Iajret commented on tff_modular/modules/custom_revolution/code/rev_deconvert_machine.dm
> +	circuit = /obj/item/circuitboard/machine/self_actualization_device
```suggestion
	circuit = /obj/item/circuitboard/machine/custom_rev_deconvert_device
```

2023-07-25 01:45 UTC, Iajret commented on tff_modular/modules/custom_revolution/code/rev_deconvert_machine.dm
> +/obj/machinery/self_actualization_device/crowbar_act(mob/living/user, obj/item/used_item)
```suggestion
/obj/machinery/custom_rev_deconvert_device/crowbar_act(mob/living/user, obj/item/used_item)
```

2023-07-30 14:26 UTC, merged